name: A Diamond Affair Interiors
favicon: null
layout_spectrum: 0.38187250192277133
typography_spectrum: 0.973488176940009
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5106068917084485
  lightness: 0.5540099833160639
  saturation: 0.3999846368096769
  rhythmicContrast: 0.9641264963429421
purpose: []
