typography_spectrum: 1
color:
  brandColors:
    - '#868581'
    - '#a2a8ab'
    - '#fefefe'
    - '#201613'
    - '#554f4b'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.63715
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Garry Tomason
  email: garry@adiamondaffair.com
name: A Diamond Affair Interiors
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'A Diamond Affair Luxury Interiors '
description: Design & Build
purpose: []
