name: A Diamond Affair Interiors
favicon: null
layout_spectrum: 0.63525
typography_spectrum: 1
title: 'A Diamond Affair Interiors - Certified Interior Designer #6827'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#868581'
    - '#a2a8ab'
    - '#fefefe'
    - '#201613'
    - '#554f4b'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
