name: A Diamond Affair Interiors
favicon: null
layout_spectrum: 0.86873
typography_spectrum: 0.90399
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050001'
    - '#5d5950'
    - '#602d13'
    - '#afc3d4'
  brandStrength: 0.375
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
